import React, { Component } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import {Login} from './Login'; 
import {Table} from 'react-bootstrap';
import {Button,ButtonToolbar,Navbar,Nav} from 'react-bootstrap';
import {AddRequest} from './AddRequest';
import {NavLink} from 'react-router-dom';

export class FieldOper extends Component{
    constructor(props){
        super(props);
        this.state={fieldoper:[],addModalShow:false}
    }

    refreshList(){
        fetch('https://localhost:44349/Api/fo')
        .then(response=>response.json()
        .then(data=>{
            this.setState({fieldoper:data})
        }))
    }

    componentDidMount(){
        this.refreshList();
    }
    componentDidUpdate(){
        this.refreshList();
    }

    //method for deleting an existing request
    deleteFo(id){
        if(window.confirm('Are you sure?')){
            fetch('https://localhost:44349/Api/fo/'+id,{
                method:'delete',
                header:{'Accept':'application/json',
            'Content-Type':'application/json'}
            })
        }
    }

    //method to logout from field operator dashboard redirecting to login page
    logout(){
        window.localStorage.clear();
        window.location.href = ("/Login");
    }

    //field operator dashboard to display all requests generated by a field operator
    render(){
        const{fieldoper}=this.state;
        let addModalClose=()=>this.setState({addModalShow:false});

        return(
            <div className="background">
            <div className="container">
            <br/>
            <br/>
            <Navbar className="navigation-bar" bg="dark" expand="lg">
            <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                <Navbar.Collapse id="responsive-navbar-nav">
                    <Nav >
                    <Navbar.Brand className="text-white">Welcome to Field Operator Dashboard!!!</Navbar.Brand>
                    </Nav>
                    <Nav pullRight>
                        <button class="btn btn-danger" onClick={this.logout}>Logout</button>
                    </Nav>
                </Navbar.Collapse>
            </Navbar>
            <Table className="mt-4 table table-sm table-dark" striped bordered hover size="sm">
                <thead>
                    <tr>
                    <th>Inspection Engineer</th>
                    <th>SME</th>
                    <th>Request Number</th>
                    <th>Date and Time</th>
                    <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {fieldoper.map(fo=>
                        <tr key={fo.Id}>
                            <td>{fo.PIEname}</td>
                            <td>{fo.SMEname}</td>
                            <td>{fo.Id}</td>
                            <td>{fo.Date_Time}</td>
                            <td>
                                <ButtonToolbar>
                                    <Button className="mr-2" variant="danger"
                                    onClick={()=>this.deleteFo(fo.Id)}>
                                    Delete
                                    </Button>
                                </ButtonToolbar>
                            </td>
                        </tr>)}

                </tbody>

            </Table>
            
            <ButtonToolbar>
                    <Button variant='primary'
                    onClick={()=>this.setState({addModalShow:true})}>
                    New Request</Button>
                    <AddRequest show={this.state.addModalShow}
                    onHide={addModalClose}/>
            </ButtonToolbar>
            </div>
            </div>          
        );
    }
}