import React, { Component } from 'react';
import {Table} from 'react-bootstrap';
import {Button,ButtonToolbar,Navbar,Nav} from 'react-bootstrap';
import {EditReqModal} from './EditReqModal';
import {NavLink} from 'react-router-dom';
import {Login} from './Login'; 
export class SME extends Component{
    constructor(props){
        super(props);
        this.state={SME:[],editModalShow:false}
    }

    refreshList(){
        fetch('https://localhost:44349/Api/fo')
        .then(response=>response.json()
        .then(data=>{
            this.setState({SME:data})
        }))
    }

    componentDidMount(){
        this.refreshList();
    }
    componentDidUpdate(){
        this.refreshList();
    }

    //method for deleting an existing request
    deleteFo(id){
        if(window.confirm('Are you sure?')){
            fetch('https://localhost:44349/Api/fo/'+id,{
                method:'delete',
                header:{'Accept':'application/json',
            'Content-Type':'application/json'}
            })
        }
    }
    //method to logout from SME dashboard redirecting to login page
    logout(){
        window.localStorage.clear();
        window.location.href = ("/Login");
    }

    //SME dashboard to display all requests generated by field operators
    render(){
        const{SME,id,piename,smename,issuecategory,productid,status,reqnum,datetime}=this.state;
        let editModalClose=()=>this.setState({editModalShow:false});

        return(
            <div className="background">
            <div className="container">
            <br/>
            <br/>
            <Navbar className="navigation-bar" bg="dark" expand="lg">
            <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                <Navbar.Collapse id="responsive-navbar-nav">
                    <Nav className="ml-auto">
                    <Navbar.Brand className="text-white">Welcome to Subject Matter Expert Dashboard!!!</Navbar.Brand>
                    </Nav>
                    <Nav pullRight>
                        <button class="btn btn-danger" onClick={this.logout}>Logout</button>
                    </Nav>
                </Navbar.Collapse>
            </Navbar>
            <Table className="mt-4 table table-sm table-dark" striped bordered hover size="sm">
                <thead>
                    <tr>
                    <th>Requestor</th>
                    <th>Request Number</th>
                    <th>Issue Category</th>
                    <th>ProductID</th>
                    <th>Status</th>
                    <th>Date and Time</th>
                    <th>Options</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    {SME.map(sme=>
                        <tr key={sme.Id}>
                            <td>{sme.PIEname}</td>
                            <td>{sme.Id}</td>
                            <td>{sme.IssueCategory}</td>
                            <td>{sme.ProductID}</td>
                            <td>{sme.Status}</td>
                            <td>{sme.Date_Time}</td>
                            <td>
                                  
                                <ButtonToolbar>
                                    <Button className="mr-2" variant="danger"
                                    onClick={()=>this.deleteFo(sme.Id)}>
                                    Delete
                                    </Button>
                                </ButtonToolbar>   
                            </td>
                            <td>     
                            <ButtonToolbar>            
                                <Button className="mr-2" variant="info"
                                    onClick={()=>this.setState({editModalShow:true,
                                    id:sme.Id,piename:sme.PIEname,smename:sme.SMEname,
                                    issuecategory:sme.IssueCategory,productid:sme.ProductID,reqnum:sme.ReqNumber,status:sme.Status,datetime:sme.Date_Time})}>
                                    Update
                                    </Button>
                                    <EditReqModal show={this.state.editModalShow}
                                        onHide={editModalClose}
                                        id={id}
                                        piename={piename}
                                        smename={smename}
                                        issuecategory={issuecategory}
                                        productid={productid}
                                        reqnum={reqnum}
                                        status={status}
                                        datetime={datetime}
                                        />
                                </ButtonToolbar>
                            </td>
                        </tr>)}
                </tbody>
            </Table>
            </div>   
            </div>
        );
    }
}
